### PR TITLE
Proofing fixes

### PR DESCRIPTION
**Pull request by robinwhittleton**
A few fixes, which should be self-descriptive from the commit messages.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! We need to add `namespace xml "http://www.w3.org/XML/1998/namespace";` to the CSS; also `ponderibus librata suis` should probably be in italics.

**Comment by robinwhittleton** [comment]
Regarding `ponderibus`, no problem but how about the other couple of instances of non-italicised Latin?

- `“<span xml:lang="la">Ibi omnis effusus labor!</span>”`
- `‘<span xml:lang="la">I nunc, et versus tecum meditare canoros.</span>’`

**Comment by acabal** [comment]
Yeah those should get italics too. Not sure why they didn't.

**Comment by robinwhittleton** [comment]
Done!

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
